### ISSUE TITLE
Average accuracy being displayed incorrectly

### ISSUE THREAD

**Issue by griffincorriher** [miaohancheng/pysmatch#3]
During testing today, I noticed that the average accuracy was not being displayed correctly.
[This line](https://github.com/miaohancheng/pysmatch/blob/5024f264aa99d36bf20228246933678ddb1612fd/pysmatch/Matcher.py#L155)
```python
 logging.info(f"Average Accuracy:{round(np.mean((self.model_accuracy) * 100),2)}% ")
```
What is being displayed:
```python
...
Model 100/1 trained. Accuracy: 86.37%
Model 80/1 trained. Accuracy: 86.30%
Model 90/1 trained. Accuracy: 84.81%
Average Accuracy:0.85% 
```

I believe should be
```python
 logging.info(f"Average Accuracy:{np.mean(self.model_accuracy):.2%} ")
```
```python
Average Accuracy:85.25% 
```

**Comment by miaohancheng** [comment]
This is my oversight. I forgot to check the output content during testing. There will be a version fix soon.
